alias qwe='~/.start.sh'
alias dotfiles='git --git-dir=/home/kozuki-oden/dotfiles --work-tree=/home/kozuki-oden'
alias dotfiles='git --git-dir=/home/kozuki-oden/dotfiles --work-tree=/home/kozuki-oden'
alias dotfiles='git --git-dir=/home/kozuki-oden/dotfiles --work-tree=/home/kozuki-oden'
alias dotfiles='git --git-dir=/home/kozuki-oden/dotfiles --work-tree=/home/kozuki-oden'
